
-- Magnitude Analsyis
-- Compare the measure values by categries.(it help us understand the importance of different categories)(Sum of Measure by Dimension)
-- Compining any measure with any dimension you can call it,it's a new insight

-- Find total customers by countries
select country,count(customer_key) as total_customers from gold.dim_customers
group by country
order by total_customers  desc


-- Find total customers by gender
select gender,count(customer_key) as total_customers from gold.dim_customers
group by gender
order by total_customers  desc



-- Find total products by category
select category,count(product_key) as total_products from gold.dim_products
group by category
order by total_products desc



-- What is the average costs in each category?
select category, avg(cost) as avg_costs from gold.dim_products
group by category 
order by avg_costs desc


-- What is the total revenue generated for each category?

select category , sum(sales_amount) as total_revenue  from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key   -- I usually start with the fact then left join the diemnsion to it
group by category
order by total_revenue desc


-- What is the total revenue generated by each customer?

select c.customer_key, c.first_name, c.last_name,
sum(f.sales_amount) as total_revenue from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by c.customer_key,c.first_name,c.last_name
order by total_revenue desc

-- What is the distribution of items sold across countries?
select c.country,
sum(f.quantity) as total_sold_items from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by c.country
order by total_sold_items desc
 